#include "openvpn_server.hpp"

#include <cerrno>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <signal.h>
#include <sstream>
#include <string>
#include <thread>
#include <tuple>
#include <utility>
#include <vector>
#include <sys/wait.h>
#include <unistd.h>

#include <ace/Log_Msg.h>
#include <ace/Process.h>

namespace server {
namespace openvpn {

// ─────────────────────── Pure helpers ───────────────────────────────

bool cidr_to_net_mask(const std::string& cidr,
                      std::string& net, std::string& mask) {
    auto slash = cidr.find('/');
    if (slash == std::string::npos) return false;
    net = cidr.substr(0, slash);
    if (net.empty()) return false;
    char* end = nullptr;
    long prefix = std::strtol(cidr.c_str() + slash + 1, &end, 10);
    if (prefix < 0 || prefix > 32 || end == cidr.c_str() + slash + 1)
        return false;
    std::uint32_t m = prefix == 0 ? 0u : (0xFFFFFFFFu << (32 - prefix));
    std::ostringstream ss;
    ss << ((m >> 24) & 0xFF) << '.' << ((m >> 16) & 0xFF) << '.'
       << ((m >> 8) & 0xFF)  << '.' << (m & 0xFF);
    mask = ss.str();
    return true;
}

std::string build_server_config(const OpenVpnServerConfig& c) {
    std::string net, mask;
    if (!cidr_to_net_mask(c.subnet, net, mask)) return "";
    std::ostringstream ss;
    ss << "# Auto-generated by iot-cloudd (server::openvpn) — do not edit.\n";
    ss << "mode server\n";
    ss << "tls-server\n";
    ss << "dev "   << c.dev   << "\n";
    ss << "proto " << c.proto << "\n";
    ss << "port "  << c.port  << "\n";
    ss << "topology subnet\n";
    ss << "server " << net << " " << mask << "\n";
    ss << "ca   " << c.ca_path   << "\n";
    ss << "cert " << c.cert_path << "\n";
    ss << "key  " << c.key_path  << "\n";
    ss << "dh none\n";                       // ECDH — no dh.pem needed
    ss << "cipher " << c.cipher  << "\n";
    ss << "keepalive 10 120\n";
    ss << "persist-key\n";
    ss << "persist-tun\n";
    ss << "management 127.0.0.1 " << c.mgmt_port << "\n";
    ss << "verb " << c.verb << "\n";
    return ss.str();
}

namespace {

std::string write_temp_config(const std::string& body) {
    auto try_open = [](std::string tmpl) -> std::pair<int, std::string> {
        std::vector<char> buf(tmpl.begin(), tmpl.end());
        buf.push_back('\0');
        int fd = ::mkstemps(buf.data(), 5);   // 5 == strlen(".conf")
        if (fd >= 0) return { fd, std::string(buf.data()) };
        return { -1, std::string{} };
    };
    std::string base;
    if (const char* t = ::getenv("TMPDIR"); t && *t) base = t;
    else base = "/tmp";
    auto [fd, path] = try_open(base + "/ovpn-server-XXXXXX.conf");
    if (fd < 0) std::tie(fd, path) = try_open("ovpn-server-XXXXXX.conf");
    if (fd < 0) return {};
    ::write(fd, body.data(), body.size());
    ::close(fd);
    return path;
}

}  // namespace

// ─────────────────────── OpenVpnServer ──────────────────────────────

OpenVpnServer::OpenVpnServer(OpenVpnServerConfig cfg, std::string openvpn_path)
    : m_cfg(std::move(cfg)), m_openvpn_path(std::move(openvpn_path)) {}

OpenVpnServer::~OpenVpnServer() {
    stop();
    if (!m_config_path.empty()) ::unlink(m_config_path.c_str());
}

bool OpenVpnServer::start() {
    if (running()) return true;             // already up — idempotent

    const std::string body = build_server_config(m_cfg);
    if (body.empty()) {
        ACE_ERROR_RETURN((LM_ERROR,
                          ACE_TEXT("%D cloudd:thread:%t %M %N:%l openvpn server "
                                   "config render failed (subnet=%C)\n"),
                          m_cfg.subnet.c_str()),
                         false);
    }
    if (!m_config_path.empty()) ::unlink(m_config_path.c_str());
    m_config_path = write_temp_config(body);
    if (m_config_path.empty()) {
        ACE_ERROR_RETURN((LM_ERROR,
                          ACE_TEXT("%D cloudd:thread:%t %M %N:%l openvpn server "
                                   "write_temp_config failed\n")),
                         false);
    }

    ACE_Process_Options opts;
    std::ostringstream cmd;
    cmd << m_openvpn_path << " --config " << m_config_path;
    opts.command_line("%s", cmd.str().c_str());

    ACE_Process proc;
    pid_t p = proc.spawn(opts);
    if (p == ACE_INVALID_PID) {
        ACE_ERROR_RETURN((LM_ERROR,
                          ACE_TEXT("%D cloudd:thread:%t %M %N:%l openvpn spawn(%C)"
                                   " failed errno=%d\n"),
                          m_openvpn_path.c_str(), errno),
                         false);
    }
    m_pid = p;
    m_exit_code = -1;
    ACE_DEBUG((LM_INFO,
               ACE_TEXT("%D cloudd:thread:%t %M %N:%l openvpn server up pid=%d "
                        "port=%d subnet=%C\n"),
               static_cast<int>(m_pid), m_cfg.port, m_cfg.subnet.c_str()));
    return true;
}

bool OpenVpnServer::running() {
    if (m_pid == 0) return false;
    int status = 0;
    pid_t r = ::waitpid(m_pid, &status, WNOHANG);
    if (r == 0) return true;                 // still alive
    if (r < 0) { m_pid = 0; return false; }  // ECHILD — treat as gone
    if (WIFEXITED(status))        m_exit_code = WEXITSTATUS(status);
    else if (WIFSIGNALED(status)) m_exit_code = 128 + WTERMSIG(status);
    m_pid = 0;
    return false;
}

void OpenVpnServer::stop(std::chrono::milliseconds grace) {
    if (m_pid == 0) return;
    ::kill(m_pid, SIGTERM);
    const auto deadline = std::chrono::steady_clock::now() + grace;
    while (std::chrono::steady_clock::now() < deadline) {
        if (!running()) break;
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }
    if (m_pid != 0) {
        ::kill(m_pid, SIGKILL);
        int status = 0;
        ::waitpid(m_pid, &status, 0);
        m_pid = 0;
    }
    if (!m_config_path.empty()) {
        ::unlink(m_config_path.c_str());
        m_config_path.clear();
    }
}

}  // namespace openvpn
}  // namespace server
