#include "openvpn_server.hpp"

#include <cerrno>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <ctime>     // strptime/mktime — Last-Ref freshness parse
#include <signal.h>
#include <sstream>
#include <string>
#include <thread>
#include <tuple>
#include <utility>
#include <vector>
#include <fcntl.h>
#include <sys/wait.h>
#include <unistd.h>

#include <ace/Log_Msg.h>
#include <ace/Process.h>

namespace server {
namespace openvpn {

// ─────────────────────── Pure helpers ───────────────────────────────

bool cidr_to_net_mask(const std::string& cidr,
                      std::string& net, std::string& mask) {
    auto slash = cidr.find('/');
    if (slash == std::string::npos) return false;
    net = cidr.substr(0, slash);
    if (net.empty()) return false;
    char* end = nullptr;
    long prefix = std::strtol(cidr.c_str() + slash + 1, &end, 10);
    if (prefix < 0 || prefix > 32 || end == cidr.c_str() + slash + 1)
        return false;
    std::uint32_t m = prefix == 0 ? 0u : (0xFFFFFFFFu << (32 - prefix));
    std::ostringstream ss;
    ss << ((m >> 24) & 0xFF) << '.' << ((m >> 16) & 0xFF) << '.'
       << ((m >> 8) & 0xFF)  << '.' << (m & 0xFF);
    mask = ss.str();
    return true;
}

std::map<std::string, VpnRoute>
parse_status_routing_table(const std::string& status,
                           std::time_t now, int max_age_secs) {
    std::map<std::string, VpnRoute> out;

    // Isolate the ROUTING TABLE section: from its header to the next section
    // ("GLOBAL STATS") or EOF. CLIENT LIST is left out on purpose — its rows
    // lead with the real address, not the virtual IP.
    auto rt = status.find("ROUTING TABLE");
    if (rt == std::string::npos) return out;
    auto secEnd = status.find("GLOBAL STATS", rt);
    if (secEnd == std::string::npos) secEnd = status.size();

    const std::string suffix = "@cloud.local";
    std::istringstream iss(status.substr(rt, secEnd - rt));
    std::string line;
    while (std::getline(iss, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();

        // Data row = "Virtual Address,Common Name,Real Address,Last Ref".
        // Split on the first 3 commas; the remainder is Last Ref (asctime, no
        // comma). The title line ("ROUTING TABLE") has no commas → skipped; the
        // header line's CN field is "Common Name" → fails the rpi… check below.
        std::string field[4];
        std::size_t start = 0;
        int n = 0;
        for (; n < 3; ++n) {
            auto c = line.find(',', start);
            if (c == std::string::npos) break;
            field[n] = line.substr(start, c - start);
            start = c + 1;
        }
        if (n < 3) continue;                  // not a 4-column data row
        field[3] = line.substr(start);        // Last Ref

        const std::string& vip = field[0];
        const std::string& cn  = field[1];
        if (cn.compare(0, 3, "rpi") != 0) continue;
        auto at = cn.find(suffix);
        if (at == std::string::npos || at <= 3) continue;
        std::string serial = cn.substr(3, at - 3);
        std::string wan    = field[2].substr(0, field[2].find(':'));  // strip :port

        // Freshness drop. Last Ref is asctime() local time, e.g.
        // "Wed Jun 25 02:30:00 2026". mktime() reads it in the process TZ —
        // the SAME host/TZ OpenVPN wrote it in (cloudd polls 127.0.0.1) — so
        // `now - ref` is a correct age regardless of zone. Unparseable → keep.
        if (max_age_secs > 0 && !field[3].empty()) {
            std::tm tm{};
            if (::strptime(field[3].c_str(), "%a %b %d %H:%M:%S %Y", &tm)) {
                tm.tm_isdst = -1;
                std::time_t ref = ::mktime(&tm);
                if (ref != static_cast<std::time_t>(-1) &&
                    now - ref > max_age_secs) {
                    continue;                 // stale route → tunnel down
                }
            }
        }

        if (serial.empty() || vip.empty()) continue;
        if (serial.find_first_of(",\r\n \t") != std::string::npos) continue;
        if (vip.find_first_of(",\r\n \t")    != std::string::npos) continue;
        if (wan.find_first_of(",\r\n \t")    != std::string::npos) wan.clear();
        out[serial] = VpnRoute{vip, wan};
    }
    return out;
}

std::string build_server_config(const OpenVpnServerConfig& c) {
    std::string net, mask;
    if (!cidr_to_net_mask(c.subnet, net, mask)) return "";
    std::ostringstream ss;
    ss << "# Auto-generated by iot-cloudd (server::openvpn) — do not edit.\n";
    ss << "mode server\n";
    ss << "tls-server\n";
    ss << "dev "   << c.dev   << "\n";
    // The operator-facing proto is the plain base form ("tcp"/"udp") — that's
    // also what the device/client uses. But OpenVPN's TCP *server socket* needs
    // the explicit "-server" form to LISTEN (mode server + tls-server set the
    // TLS role, not the socket direction), so add it here for TCP. udp needs no
    // suffix; an already-suffixed value (legacy "tcp-server") passes through.
    auto server_socket_proto = [](const std::string& p) -> std::string {
        if (p == "tcp" || p == "tcp4" || p == "tcp6") return p + "-server";
        return p;
    };
    ss << "proto " << server_socket_proto(c.proto) << "\n";
    ss << "port "  << c.port  << "\n";
    ss << "topology subnet\n";
    ss << "server " << net << " " << mask << "\n";
    // Multi-tenant (P3c): per-client static IPs via client-config-dir. Each
    // device's CCD file (named by its cert CN) does ifconfig-push to an address
    // in its tenant's /24, so the inter-tenant nft drops (P3b) match. Emitted
    // only when configured — a single-tenant deployment is unchanged.
    if (!c.ccd_dir.empty()) ss << "client-config-dir " << c.ccd_dir << "\n";
    // Push a DNS resolver to clients (when configured) so the device learns
    // it in the PUSH_REPLY and surfaces vpn.assigned.dns. topology subnet
    // already auto-pushes route-gateway + ifconfig (ip+netmask).
    if (!c.dns.empty()) {
        ss << "push \"dhcp-option DNS " << c.dns << "\"\n";
    }
    ss << "ca   " << c.ca_path   << "\n";
    ss << "cert " << c.cert_path << "\n";
    ss << "key  " << c.key_path  << "\n";
    // Revocation: when a CRL is configured, openvpn rejects any client cert
    // listed in it. Conditional — emitted only when set, so a deployment
    // without a CRL is unchanged (and openvpn won't refuse to start on a
    // missing crl-verify file). The CA writes the CRL; iot-cloudd points
    // c.crl at it once it exists. See apps/docs/tdd-device-transfer.md.
    if (!c.crl.empty()) ss << "crl-verify " << c.crl << "\n";
    ss << "dh none\n";                       // ECDH — no dh.pem needed
    ss << "cipher " << c.cipher  << "\n";
    // ping every 10s; declare a peer dead after 60s of silence. On the SERVER
    // OpenVPN uses 2x the restart value, so a hard-powered-off client's session
    // (no clean disconnect) is reaped in ~120s instead of ~240s. The per-device
    // "VPN up" view in the cloud UI is made accurate much sooner (~30s) by the
    // Last-Ref freshness filter in parse_status_routing_table(); this modest
    // tighten just stops a dead session lingering — kept conservative so a
    // flaky-link device isn't dropped from a healthy tunnel.
    ss << "keepalive 10 60\n";
    ss << "persist-key\n";
    ss << "persist-tun\n";
    ss << "management 127.0.0.1 " << c.mgmt_port << "\n";
    ss << "verb " << c.verb << "\n";
    return ss.str();
}

namespace {

std::string write_temp_config(const std::string& body) {
    auto try_open = [](std::string tmpl) -> std::pair<int, std::string> {
        std::vector<char> buf(tmpl.begin(), tmpl.end());
        buf.push_back('\0');
        int fd = ::mkstemps(buf.data(), 5);   // 5 == strlen(".conf")
        if (fd >= 0) return { fd, std::string(buf.data()) };
        return { -1, std::string{} };
    };
    std::string base;
    if (const char* t = ::getenv("TMPDIR"); t && *t) base = t;
    else base = "/tmp";
    auto [fd, path] = try_open(base + "/ovpn-server-XXXXXX.conf");
    if (fd < 0) std::tie(fd, path) = try_open("ovpn-server-XXXXXX.conf");
    if (fd < 0) return {};
    ::write(fd, body.data(), body.size());
    ::close(fd);
    return path;
}

}  // namespace

// ─────────────────────── OpenVpnServer ──────────────────────────────

OpenVpnServer::OpenVpnServer(OpenVpnServerConfig cfg, std::string openvpn_path)
    : m_cfg(std::move(cfg)), m_openvpn_path(std::move(openvpn_path)) {}

OpenVpnServer::~OpenVpnServer() {
    stop();
    if (!m_config_path.empty()) ::unlink(m_config_path.c_str());
}

bool OpenVpnServer::reconfigure(const OpenVpnServerConfig& cfg) {
    // Compare on the RENDERED config, not field-by-field: it's the single
    // source of truth for what actually reaches openvpn, so a change to any
    // knob that affects the file (and only those) triggers a restart. A
    // redundant ds write (same effective config) renders identically → no-op,
    // so a healthy tunnel isn't bounced.
    if (build_server_config(cfg) == build_server_config(m_cfg)) return false;
    m_cfg = cfg;
    if (running()) stop();                  // caller restarts with the new cfg
    return true;
}

bool OpenVpnServer::start() {
    if (running()) return true;             // already up — idempotent

    const std::string body = build_server_config(m_cfg);
    if (body.empty()) {
        ACE_ERROR_RETURN((LM_ERROR,
                          ACE_TEXT("%D cloudd:thread:%t %M %N:%l openvpn server "
                                   "config render failed (subnet=%C)\n"),
                          m_cfg.subnet.c_str()),
                         false);
    }
    if (!m_config_path.empty()) ::unlink(m_config_path.c_str());
    m_config_path = write_temp_config(body);
    if (m_config_path.empty()) {
        ACE_ERROR_RETURN((LM_ERROR,
                          ACE_TEXT("%D cloudd:thread:%t %M %N:%l openvpn server "
                                   "write_temp_config failed\n")),
                         false);
    }

    ACE_Process_Options opts;
    std::ostringstream cmd;
    cmd << m_openvpn_path << " --config " << m_config_path;
    opts.command_line("%s", cmd.str().c_str());

    // Capture the child's stdout+stderr to a file so a failed start is
    // diagnosable. openvpn(8) prints its exit reason there (e.g. missing
    // TUN device, bad cert) — otherwise it vanishes onto the container's
    // stdout, invisible to the cloudd log. Truncated fresh on every start.
    if (m_log_path.empty()) {
        const char* t = ::getenv("TMPDIR");
        std::string base = (t && *t) ? t : "/tmp";
        m_log_path = base + "/ovpn-server.log";
    }
    int lfd = ::open(m_log_path.c_str(),
                     O_CREAT | O_TRUNC | O_WRONLY, 0644);
    if (lfd >= 0) {
        // Keep stdin inherited; redirect stdout + stderr to the capture file.
        opts.set_handles(ACE_STDIN, lfd, lfd);
    }

    ACE_Process proc;
    pid_t p = proc.spawn(opts);
    if (lfd >= 0) ::close(lfd);   // child has its own dup'd descriptor now
    if (p == ACE_INVALID_PID) {
        ACE_ERROR_RETURN((LM_ERROR,
                          ACE_TEXT("%D cloudd:thread:%t %M %N:%l openvpn spawn(%C)"
                                   " failed errno=%d\n"),
                          m_openvpn_path.c_str(), errno),
                         false);
    }
    m_pid = p;
    m_exit_code = -1;
    ACE_DEBUG((LM_INFO,
               ACE_TEXT("%D cloudd:thread:%t %M %N:%l openvpn server up pid=%d "
                        "port=%d subnet=%C\n"),
               static_cast<int>(m_pid), m_cfg.port, m_cfg.subnet.c_str()));
    return true;
}

bool OpenVpnServer::running() {
    if (m_pid == 0) return false;
    int status = 0;
    pid_t r = ::waitpid(m_pid, &status, WNOHANG);
    if (r == 0) return true;                 // still alive
    if (r < 0) { m_pid = 0; return false; }  // ECHILD — treat as gone
    if (WIFEXITED(status))        m_exit_code = WEXITSTATUS(status);
    else if (WIFSIGNALED(status)) m_exit_code = 128 + WTERMSIG(status);
    m_pid = 0;
    return false;
}

std::string OpenVpnServer::log_tail(std::size_t max_bytes) const {
    if (m_log_path.empty()) return {};
    int fd = ::open(m_log_path.c_str(), O_RDONLY);
    if (fd < 0) return {};
    off_t end = ::lseek(fd, 0, SEEK_END);
    if (end <= 0) { ::close(fd); return {}; }
    off_t start = (static_cast<std::size_t>(end) > max_bytes)
                ? end - static_cast<off_t>(max_bytes) : 0;
    ::lseek(fd, start, SEEK_SET);
    std::string out;
    out.resize(static_cast<std::size_t>(end - start));
    ssize_t n = ::read(fd, &out[0], out.size());
    ::close(fd);
    if (n <= 0) return {};
    out.resize(static_cast<std::size_t>(n));
    return out;
}

void OpenVpnServer::stop(std::chrono::milliseconds grace) {
    if (m_pid == 0) return;
    ::kill(m_pid, SIGTERM);
    const auto deadline = std::chrono::steady_clock::now() + grace;
    while (std::chrono::steady_clock::now() < deadline) {
        if (!running()) break;
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }
    if (m_pid != 0) {
        ::kill(m_pid, SIGKILL);
        int status = 0;
        ::waitpid(m_pid, &status, 0);
        m_pid = 0;
    }
    if (!m_config_path.empty()) {
        ::unlink(m_config_path.c_str());
        m_config_path.clear();
    }
}

}  // namespace openvpn
}  // namespace server
