-- Schema published by the iot client. Drop this file (and any sibling
-- *.lua) under ds-server's `ds-schema-dir=` path — default
-- `/etc/iot/ds-schemas/` — and ds-server will validate every set/get
-- against it. Get on a missing key returns the schema default (when
-- declared); set is rejected with SchemaRejected (0x8004) on a type
-- mismatch or out-of-range integer.
--
-- Each schema entry's `keys` table is keyed by the FULL key name
-- (the optional `namespace` field is informational). When two
-- files claim the same key, last-loaded wins — ds-server logs a
-- WARNING so silent ownership collisions are visible.
--
-- Note: `iot.server.uri` has no `default` on purpose. The iot binary
-- treats absence as "fall back to the security-object .lua file";
-- declaring a default here would shadow that fallback for every run.

return {
  namespace = "iot",
  keys = {
    -- Device-side default/fallback registration lifetime (s). The effective
    -- value is normally the one the cloud pushes at bootstrap (cloud.dm.lifetime,
    -- default 90 — sized so the registration Update doubles as a NAT keepalive;
    -- see cloud.lua). Kept aligned at 90 so a pre-bootstrap/direct-Register run
    -- behaves the same.
    ["iot.lifetime"]   = {
        access  = "Admin",
      type    = "integer",
      default = 90,
      min     = 0,
      max     = 2592000,     -- 30 days; LwM2M Registration lifetime cap
    },
    ["iot.endpoint"]   = {
        access  = "Admin",
      type    = "string",
      default = "urn:dev:client-1",
    },
    ["iot.server.uri"] = {
        access  = "Admin",
      type    = "string",
    },
    -- Bootstrap server URI the client connects to (e.g.
    -- coaps://cloud.example.com:5684). ds-driven: the client reads this
    -- (falling back to a bs= CLI arg) and re-bootstraps when it changes.
    ["iot.bs.uri"]     = {
        access  = "Admin",
      type    = "string",
    },
    ["iot.binding"]    = {
        access  = "Admin",
      type    = "string",
      default = "U",
    },
    ["iot.identity"]   = {
        access  = "Admin",
      type    = "opaque",
    },
    ["iot.observable"] = {
        access  = "Admin",
      type    = "boolean",
      default = true,
    },

    -- ── PSK provisioning (serial-derived endpoint + write-only PSK) ──
    -- The lwm2m client runs as user `engineer`; the PSK keys are
    -- write-only (read_acl=gid:engineer) so ds-cli (root) cannot read
    -- them. Commissioning is gated behind iot.dev.mode (the ds-server
    -- bypasses these ACLs while dev-mode is on). See
    -- apps/docs/tdd-psk-provisioning.md.
    --
    -- Hardware serial number. On a Raspberry Pi the client auto-fills
    -- this at startup from /proc/device-tree/serial-number; on other
    -- hardware the installer enters it on the device-ui Config page
    -- (written via httpd under dev-mode). It is the LwM2M endpoint and
    -- the on-the-wire BS DTLS PSK identity, so it stays readable.
    ["iot.serial"] = {
        access    = "Admin",
        type      = "string",
        default   = "",
        write_acl = {"gid:engineer"},
    },
    -- Commissioning flag. While true the ds-server bypasses read_acl /
    -- write_acl on the PSK keys so an engineer can generate, read back
    -- and provision credentials. Defaults true for now (simple dev
    -- commissioning out of the box); set false to lock the secrets down.
    ["iot.dev.mode"] = {
        access    = "Admin",
        type      = "boolean",
        default   = true,
        write_acl = {"gid:engineer"},
    },
    -- Bootstrap (BS) PSK identity. Normally = raw serial (derived on the
    -- wire as sha256(endpoint)[:32]). When iot.bs.psk.override is true this
    -- holds the operator-supplied identity used VERBATIM, for third-party
    -- bootstrap servers that mint their own identity/PSK pair.
    ["iot.bs.psk.identity"] = {
        access    = "Admin",
        type      = "string",
        default   = "",
        write_acl = {"gid:engineer"},
        read_acl  = {"gid:engineer"},
    },
    -- Third-party BS PSK override. When true the client uses
    -- iot.bs.psk.identity verbatim (not the sha256(endpoint) derivation)
    -- together with iot.bs.psk.key for the bootstrap DTLS handshake. The
    -- DM (Device-Management) credential path is unaffected. Off by default
    -- → identical to the legacy derived-identity behaviour. Non-secret mode
    -- flag (like iot.dev.mode): write-gated but READABLE, so the device-ui
    -- toggle reflects the true state even outside commissioning mode.
    ["iot.bs.psk.override"] = {
        access    = "Admin",
        type      = "boolean",
        default   = false,
        write_acl = {"gid:engineer"},
    },
    -- Bootstrap (BS) PSK secret. 32 bytes, hex-encoded (64 chars).
    -- Generated by device-ui, written under dev-mode. Write-only.
    ["iot.bs.psk.key"] = {
        access    = "Admin",
        type      = "opaque",
        write_acl = {"gid:engineer"},
        read_acl  = {"gid:engineer"},
    },
    -- Device-Management (DM) PSK identity = rpi<serial>@cloud.local,
    -- delivered by the bootstrap server and stored by the client.
    ["iot.dm.psk.identity"] = {
        access    = "Admin",
        type      = "string",
        default   = "",
        write_acl = {"gid:engineer"},
        read_acl  = {"gid:engineer"},
    },
    -- Device-Management (DM) PSK secret, delivered by bootstrap.
    -- Write-only.
    ["iot.dm.psk.key"] = {
        access    = "Admin",
        type      = "opaque",
        write_acl = {"gid:engineer"},
        read_acl  = {"gid:engineer"},
    },

    -- ── LwM2M connection lifecycle (client → device-ui) ──────────────
    -- The lwm2m client publishes its live connection progress here so the
    -- device-ui can show real-time status. Single string, read-only to the
    -- UI. Machine tokens (the UI maps these to professional labels):
    --   idle           - not started / no link               ("Disconnected")
    --   bootstrapping  - establishing secure channel to BS    ("Bootstrap: Connecting")
    --   bootstrapped   - BS channel up; exchanging /bs writes  ("Bootstrap: Connected")
    --   dm-connecting  - establishing secure channel to DM     ("Device Management: Connecting")
    --   dm-connected   - DM channel up; Register in flight     ("Device Management: Connected")
    --   registered     - registered with DM                    ("LwM2M Connected")
    --   failed         - registration rejected / link failed   ("Connection Failed")
    ["iot.conn.state"] = {
        access  = "Viewer",
        type    = "string",
        default = "idle",
    },

    -- Device-transfer (customer re-home) lifecycle, surfaced in the device-ui
    -- Advanced -> Transfer panel: "idle" / "wiping" / "awaiting-commission".
    -- Written by iot-transfer (runs as engineer); readable so the UI reflects
    -- when the device has been wiped and is parked for the new owner to
    -- commission. See apps/docs/tdd-device-transfer.md.
    ["iot.transfer.state"] = {
        access    = "Viewer",
        type      = "string",
        default   = "idle",
        write_acl = {"gid:engineer"},
    },

    -- ── mangOH Yellow sensor telemetry (iot-sensord → ds → IPSO/UI) ──
    -- The privileged iot-sensord daemon owns the I2C bus, reads the onboard
    -- BME680 / BMI160 / light sensors and publishes their latest values here.
    -- The lwm2m client mirrors them into IPSO objects (3303/3304/3315/3301/
    -- 3313/3334) for the cloud, and the device-ui shows them locally. Scalars
    -- are formatted decimal strings; accel/gyro are "x,y,z" raw counts. See
    -- apps/docs/tdd-mangoh-yellow-sensors.md.
    ["iot.sensor.temp"] = {        -- BME680 temperature, deg C
        access  = "Viewer",
        type    = "string",
        default = "",
    },
    ["iot.sensor.humidity"] = {    -- BME680 relative humidity, %RH
        access  = "Viewer",
        type    = "string",
        default = "",
    },
    ["iot.sensor.pressure"] = {    -- BME680 barometric pressure, Pa
        access  = "Viewer",
        type    = "string",
        default = "",
    },
    ["iot.sensor.lux"] = {         -- ambient light, lux
        access  = "Viewer",
        type    = "string",
        default = "",
    },
    ["iot.sensor.accel"] = {       -- BMI160 accel "x,y,z" raw int16 counts
        access  = "Viewer",
        type    = "string",
        default = "",
    },
    ["iot.sensor.gyro"] = {        -- BMI160 gyro "x,y,z" raw int16 counts
        access  = "Viewer",
        type    = "string",
        default = "",
    },
    ["iot.sensor.version"] = {     -- bumped each sample for device-ui long-poll
        access  = "Viewer",
        type    = "integer",
        default = 0,
    },

    -- ── DM Server URI (client → device-ui) ───────────────────────────
    -- The lwm2m client publishes the bootstrap-delivered DM Server URI
    -- (Security Object RID 0 of the non-bootstrap PSK account) here once
    -- the bootstrap commit lands, so the device-ui can show the URI the
    -- device actually registered to. Single string, read-only to the UI.
    ["iot.dm.uri"] = {
        access  = "Viewer",
        type    = "string",
        default = "",
    },

    -- ── OTA software update (mirrors LwM2M Object 5 onto ds) ──────────
    -- Self-update trigger: device-ui (or the Object-5 RID2 apply) sets the
    -- .ipk URL here; the lwm2m client watches it and runs iot-ota-apply.
    ["iot.update.request"] = {
        access  = "Admin",
        type    = "string",
        default = "",
    },
    -- Download retry budget for iot-ota-stage. The firmware download rides the
    -- public WAN (not the VPN tunnel), so a flaky uplink is retried with
    -- backoff + resume up to this many attempts before failing the campaign.
    ["iot.update.retries"] = {
        access  = "Admin",
        type    = "integer",
        default = 5,
    },
    -- Apply progress, written by iot-ota-apply, read by device-ui and
    -- mirrored into Object 5 (/5/0/3, /5/0/5) on client (re)start so a
    -- post-restart server readback reflects the outcome.
    ["iot.update.state"] = {        -- 0 idle,1 downloading,2 downloaded,3 updating,
        access  = "Admin",          -- 4 writing-bank,5 awaiting-confirm (A/B, Phase 2)
        type    = "integer",
        default = 0,
    },
    ["iot.update.result"] = {       -- 0 initial,1 success,2 rolled-back (A/B),
        access  = "Admin",          -- 5 integrity,8 uri,9 install,
                                    -- 10 skipped (offered not newer — downgrade refused)
        type    = "integer",
        default = 0,
    },
    -- Human-readable cause for a terminal iot.update.result (e.g. "no .ipk in
    -- bundle", "sha256 mismatch"), written by iot-ota-stage / iot-swupdate next
    -- to the result code and cleared at campaign start. Read by device-ui and
    -- served to the cloud on /5/0/26 (vendor resource) so the cloud Update
    -- Status row can say WHY a campaign failed, not just that it did.
    ["iot.update.reason"] = {
        access  = "Admin",
        type    = "string",
        default = "",
    },
    -- Download progress 0..100, written by iot-ota-stage during the download
    -- (bytes-on-disk / Content-Length). Stays 0 when the size is unknown (the
    -- device-ui then shows an indeterminate bar). 100 = fully downloaded.
    ["iot.update.progress"] = {
        access  = "Admin",
        type    = "integer",
        default = 0,
    },
    -- Human label for the artifact being applied (e.g.
    -- "iot-bundle-1.1.0-raspberrypi3-64.tar.gz (1.1.0)"), written by
    -- iot-ota-stage. Shown in the device-ui Software Update status.
    ["iot.update.package"] = {
        access  = "Admin",
        type    = "string",
        default = "",
    },

    -- A/B image OTA (Phase 2). Which rootfs bank is running, and whether this
    -- boot has been health-checked + confirmed good (else the bootloader rolls
    -- back to the other bank on the next boot). Written by iot-ota-confirm.
    -- See apps/docs/tdd-ab-image-ota.md.
    ["iot.boot.bank"] = {           -- "A" | "B" | "" (single-rootfs / non-RAUC)
        access  = "Admin",
        type    = "string",
        default = "",
    },
    ["iot.boot.confirmed"] = {      -- this boot marked good (mark-good done)
        access  = "Admin",
        type    = "boolean",
        default = false,
    },
    -- Both A/B banks for the device-ui Software page: a JSON array
    --   [{ "bootname":"A", "slot":"rootfs.0", "version":"1.2.0",
    --      "state":"good", "booted":true }, { ...B... }]
    -- Written by iot-ota-confirm at boot (and by iot-bank-switch after a
    -- mark-active). Empty on a single-rootfs / non-RAUC image.
    ["iot.boot.banks"] = {
        access  = "Admin",
        type    = "string",
        default = "",
    },
    -- Bank-switch trigger: device-ui writes the TARGET bootname ("A"|"B", or
    -- "other" for the inactive bank). The lwm2m client watches it and runs
    -- iot-bank-switch (root, via systemd-run), which `rauc status mark-active`s
    -- that bank and reboots. The bootloader's boot-attempts counter rolls back
    -- to the previous bank if the new one fails to come up. Cleared after use.
    ["iot.boot.switch.request"] = {
        access  = "Admin",
        type    = "string",
        default = "",
    },

    -- data-store self-benchmark summary (JSON), written by ds-bench at the end
    -- of a run: { config, mem:{rss_kb,hwm_kb}, per-op {ops,p50,p95,p99} }.
    -- Read via `ds-cli get ds.bench.summary` or surfaced in the UI.
    -- See modules/data-store/docs/benchmark.md.
    ["ds.bench.summary"] = {
        access  = "Admin",
        type    = "string",
        default = "",
    },
    ["iot.update.version"] = {      -- installed package version after apply
        access  = "Admin",
        type    = "string",
        default = "",
    },

    -- Running application/release version (e.g. "1.1.0+ab12cd3"). Written by
    -- iot-httpd at startup from its baked-in IOT_VERSION, so the UI shows what's
    -- actually installed — after an OTA the restarted binary self-reports the
    -- new version. Loaded by both the device and cloud ds-server.
    ["iot.version"] = {
        access  = "Admin",
        type    = "string",
        default = "",
    },

    -- Applied config/schema generation (OTA migration marker). iot-swupdate
    -- runs /usr/share/iot/migrations/NNNN-*.sh with NNNN > this value after an
    -- opkg upgrade, then bumps it. 0 = baseline (no migration applied yet).
    -- See apps/docs/tdd-yocto-swupdate.md §11.
    ["iot.config.version"] = {
        access  = "Admin",
        type    = "integer",
        default = 0,
    },

    -- Log level for all iot daemons.  Each daemon reads this key
    -- and adjusts its ACE_Log_Msg priority mask at startup and on
    -- change (hot-reload).  Valid values (case-insensitive):
    --   DEBUG, INFO, WARNING, ERROR
    -- Default: INFO (production-safe; no debug noise).
    -- Global log level — fallback when per-daemon key is unset.
    ["log.level"] = {
        access  = "Admin",
      type    = "string",
      default = "INFO",
    },
    -- Per-daemon overrides (take precedence over log.level).
    ["log.level.cloudd"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    ["log.level.httpd"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    -- Device-side lwm2m client level (cloud servers use .bs/.dm below).
    ["log.level.lwm2m"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    ["log.level.lwm2m.bs"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    ["log.level.lwm2m.dm"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    ["log.level.vpn"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    ["log.level.dtls"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    -- iot-vehicled (CAN/OBD-II) + iot-mqttd (MQTT mirror) per-daemon levels.
    ["log.level.vehicle"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    ["log.level.mqtt"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    -- iot-containerd (on-device container runtime) per-daemon level.
    ["log.level.container"] = {
        access  = "Admin",
      type    = "string",
      default = "",
    },
    -- Bumped by every daemon on log flush so the cloud UI can long-poll
    -- a single key instead of round-robining through all log.*.text keys.
    ["log.version"] = {
        access  = "Viewer",
      type    = "integer",
      default = 0,
    },

    -- Recent log output (plain text, newline-separated). Each daemon
    -- writes to its own key so they don't clobber each other. The cloud
    -- UI log viewer merges all keys. Capped at ~200 lines / ~16 KB each.
    --   log.text            — iot-httpd
    --   log.cloudd.text     — iot-cloudd
    --   log.lwm2m.text      — lwm2m (device/client mode)
    --   log.lwm2m.bs.text   — lwm2m-bs (cloud bootstrap server)
    --   log.lwm2m.dm.text   — lwm2m-dm (cloud device management)
    --   log.vehicled.text   — iot-vehicled (CAN/OBD-II)
    --   log.mqttd.text      — iot-mqttd (MQTT mirror)
    --   log.containerd.text — iot-containerd (container runtime)
    ["log.text"] = {
        access  = "Viewer",
      type    = "string",
      default = "",
    },
    ["log.cloudd.text"] = {
        access  = "Viewer",
      type    = "string",
      default = "",
    },
    ["log.lwm2m.text"] = {
        access  = "Viewer",
      type    = "string",
      default = "",
    },
    ["log.lwm2m.bs.text"] = {
        access  = "Viewer",
      type    = "string",
      default = "",
    },
    ["log.lwm2m.dm.text"] = {
        access  = "Viewer",
      type    = "string",
      default = "",
    },
    ["log.vehicled.text"] = {
        access  = "Viewer",
      type    = "string",
      default = "",
    },
    ["log.mqttd.text"] = {
        access  = "Viewer",
      type    = "string",
      default = "",
    },
    ["log.containerd.text"] = {
        access  = "Viewer",
      type    = "string",
      default = "",
    },

    -- ── v2 LwM2M Send telemetry (TDD §3b #1; OFF by default) ──────────
    -- When .send.enable is true the registered DM client samples numeric
    -- vehicle.* signals (Object 33000) and pushes them as SenML packs over the
    -- direct DTLS link (LwM2M Send, POST /dp), buffered for offline backfill by
    -- the DurableSampleBuffer when .db.path names a file (empty → in-RAM).
    ["iot.telemetry.send.enable"] = {
        access = "Admin", type = "boolean", default = false, write_acl = {"uid:0"} },
    ["iot.telemetry.db.path"] = {
        access = "Admin", type = "string",  default = "" },
    ["iot.telemetry.basepath"] = {
        access = "Admin", type = "string",  default = "/33000/0/" },
    ["iot.telemetry.capacity"] = {
        access = "Admin", type = "integer", default = 1000, min = 1, max = 1000000 },
    ["iot.telemetry.maxbatch"] = {
        access = "Admin", type = "integer", default = 8,    min = 1, max = 64 },
    ["iot.telemetry.sample.secs"] = {
        access = "Admin", type = "integer", default = 5,    min = 1, max = 3600 },
    ["iot.telemetry.ttl.secs"] = {
        access = "Admin", type = "integer", default = 0,    min = 0, max = 2592000 },
  },
}
