#include "process.hpp"

#include <cerrno>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <signal.h>
#include <sstream>
#include <stdexcept>
#include <sys/stat.h>
#include <sys/wait.h>
#include <thread>
#include <tuple>
#include <unistd.h>
#include <utility>
#include <vector>

#include <ace/Log_Msg.h>
#include <ace/Process.h>

namespace openvpn_client {

// ─────────────────────── Pure helpers ───────────────────────────────

std::string build_openvpn_config(const OpenVpnConfig& c) {
    // Baseline client-mode .conf; deliberately minimal so the schema
    // stays the source of truth for tunable knobs. Order matches the
    // canonical openvpn example client.conf so a config diff against
    // a known-good baseline is easy to eyeball.
    std::ostringstream ss;
    ss << "# Auto-generated by openvpn-client L12/D5 — do not edit.\n";
    ss << "client\n";
    ss << "dev "   << c.dev          << "\n";
    ss << "proto " << c.remote_proto << "\n";
    ss << "remote " << c.remote_host << " " << c.remote_port << "\n";
    ss << "nobind\n";
    ss << "ca   " << c.ca_path       << "\n";
    ss << "cert " << c.cert_path     << "\n";
    ss << "key  " << c.key_path      << "\n";
    ss << "cipher " << c.cipher      << "\n";
    ss << "verb 3\n";
    ss << "management 127.0.0.1 " << c.mgmt_port << "\n";
    return ss.str();
}

std::string write_temp_config(const std::string& body) {
    // Try $TMPDIR → /tmp → cwd. The data-store test harness uses the
    // same fallback chain because the iot:latest dev image sometimes
    // ships without /tmp.
    auto try_open = [](std::string tmpl) -> std::pair<int, std::string> {
        std::vector<char> buf(tmpl.begin(), tmpl.end());
        buf.push_back('\0');
        int fd = ::mkstemps(buf.data(), 5);   // 5 == strlen(".conf")
        if (fd >= 0) return { fd, std::string(buf.data()) };
        return { -1, std::string{} };
    };

    std::string base;
    if (const char* env = ::getenv("TMPDIR"); env && env[0]) base = env;
    else                                                    base = "/tmp";

    auto [fd, path] = try_open(base + "/openvpn-XXXXXX.conf");
    if (fd < 0 && base == "/tmp") {
        // Try to create /tmp; some minimal containers ship without it.
        ::mkdir("/tmp", 01777);
        std::tie(fd, path) = try_open("/tmp/openvpn-XXXXXX.conf");
    }
    if (fd < 0) {
        // Last-ditch: cwd. Operators in a sandbox without writable
        // /tmp can at least see the file in their build directory.
        std::tie(fd, path) = try_open("./openvpn-XXXXXX.conf");
    }
    if (fd < 0) {
        throw std::runtime_error(
            std::string("mkstemps failed: ") + std::strerror(errno));
    }
    ssize_t wrote = 0;
    while (wrote < static_cast<ssize_t>(body.size())) {
        ssize_t n = ::write(fd, body.data() + wrote,
                            body.size() - static_cast<std::size_t>(wrote));
        if (n < 0) {
            if (errno == EINTR) continue;
            int e = errno;
            ::close(fd);
            ::unlink(path.c_str());
            throw std::runtime_error(
                std::string("write failed: ") + std::strerror(e));
        }
        wrote += n;
    }
    if (::close(fd) < 0) {
        int e = errno;
        ::unlink(path.c_str());
        throw std::runtime_error(
            std::string("close failed: ") + std::strerror(e));
    }
    return path;
}

// ─────────────────────── OpenVpnProcess ─────────────────────────────

OpenVpnProcess::OpenVpnProcess() = default;

OpenVpnProcess::~OpenVpnProcess() {
    // Best-effort cleanup: if a subprocess is still around (daemon
    // crashed before terminate()), kill + reap so we don't leak a
    // zombie openvpn. Then unlink the generated config if any.
    if (m_pid != 0 && !m_waited) {
        terminate(std::chrono::milliseconds(500));
    }
    if (!m_config_path.empty()) {
        ::unlink(m_config_path.c_str());
    }
}

bool OpenVpnProcess::spawn(const std::string&              executable,
                           const std::vector<std::string>& argv) {
    ACE_Process_Options opts;
    // ACE_Process_Options::command_line() tokenises on whitespace
    // unless an argv element is wrapped in double-quotes. Quote any
    // arg that contains whitespace so `/bin/sh -c 'echo …'` style
    // invocations land in argv[2] intact instead of being split
    // across multiple positional args.
    auto quote_if_needed = [](const std::string& s) -> std::string {
        if (s.find_first_of(" \t\n\"\\") == std::string::npos) return s;
        std::string out;
        out.push_back('"');
        for (char c : s) {
            if (c == '"' || c == '\\') out.push_back('\\');
            out.push_back(c);
        }
        out.push_back('"');
        return out;
    };
    std::ostringstream cmd;
    cmd << executable;
    // Skip argv[0] when appending — ACE composes argv[0] from the
    // executable path itself.
    for (std::size_t i = 1; i < argv.size(); ++i) {
        cmd << " " << quote_if_needed(argv[i]);
    }
    opts.command_line("%s", cmd.str().c_str());

    ACE_Process proc;
    pid_t p = proc.spawn(opts);
    if (p == ACE_INVALID_PID) {
        ACE_ERROR((LM_ERROR,
                   ACE_TEXT("%D [ovpn:%t] %M %N:%l spawn(%C) failed errno=%d\n"),
                   executable.c_str(), errno));
        return false;
    }
    m_pid = p;
    m_exit_code = -1;
    m_waited = false;
    return true;
}

bool OpenVpnProcess::spawn_openvpn(const OpenVpnConfig& cfg,
                                   const std::string&   openvpn_path) {
    std::string body = build_openvpn_config(cfg);
    try {
        m_config_path = write_temp_config(body);
    } catch (const std::exception& e) {
        ACE_ERROR((LM_ERROR,
                   ACE_TEXT("%D [ovpn:%t] %M %N:%l write_temp_config "
                            "failed: %C\n"),
                   e.what()));
        return false;
    }
    std::vector<std::string> argv;
    argv.push_back(openvpn_path);
    argv.push_back("--config");
    argv.push_back(m_config_path);
    // The schema's vpn.mgmt.port is the single source of truth for
    // the management port; pass it explicitly even though `management`
    // is also in the .conf so a config typo can't desync the parent's
    // expected port from the child's actual listen port.
    argv.push_back("--management");
    argv.push_back("127.0.0.1");
    argv.push_back(std::to_string(cfg.mgmt_port));
    return spawn(openvpn_path, argv);
}

bool OpenVpnProcess::running() {
    if (m_pid == 0 || m_waited) return false;
    int status = 0;
    pid_t r = ::waitpid(m_pid, &status, WNOHANG);
    if (r == 0) return true;             // still running
    if (r < 0)  return false;            // ECHILD / error; treat as exited
    // Child exited. Cache the code so a later wait() doesn't try
    // to reap again.
    m_waited = true;
    if (WIFEXITED(status))         m_exit_code = WEXITSTATUS(status);
    else if (WIFSIGNALED(status))  m_exit_code = -1;
    return false;
}

int OpenVpnProcess::wait() {
    if (m_waited) return m_exit_code;
    if (m_pid == 0) return -1;
    int status = 0;
    pid_t r;
    do {
        r = ::waitpid(m_pid, &status, 0);
    } while (r < 0 && errno == EINTR);
    m_waited = true;
    if (r < 0) {
        m_exit_code = -1;
        return -1;
    }
    if (WIFEXITED(status))        m_exit_code = WEXITSTATUS(status);
    else if (WIFSIGNALED(status)) m_exit_code = -1;
    return m_exit_code;
}

void OpenVpnProcess::terminate(std::chrono::milliseconds grace) {
    if (m_pid == 0 || m_waited) return;
    ::kill(m_pid, SIGTERM);
    // Poll for grace period; if still alive, SIGKILL.
    const auto deadline = std::chrono::steady_clock::now() + grace;
    while (std::chrono::steady_clock::now() < deadline) {
        if (!running()) return;          // reaped by polling waitpid
        std::this_thread::sleep_for(std::chrono::milliseconds(20));
    }
    if (!m_waited) {
        ::kill(m_pid, SIGKILL);
        wait();
    }
}

} // namespace openvpn_client
